//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "my_column")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub table_id: i32,
    pub name: String,
    pub data_type: String,
    pub is_primary_key: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::my_table::Entity",
        from = "Column::TableId",
        to = "super::my_table::Column::ObjectId",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MyTable,
}

impl Related<super::my_table::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MyTable.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
