//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "my_table")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub object_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::my_column::Entity")]
    MyColumn,
    #[sea_orm(
        belongs_to = "super::my_object::Entity",
        from = "Column::ObjectId",
        to = "super::my_object::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    MyObject,
}

impl Related<super::my_column::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MyColumn.def()
    }
}

impl Related<super::my_object::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MyObject.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
